name: Build on MacOS
env:
  version: '1.4'

on: 
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: MPlayer-${{env.version}}

      - name: List
        run: ls -l

      - name: Install dependencies
        run: brew install yasm nasm pkg-config libass ffmpeg create-dmg dylibbundler
        
      - name: Build
        run: |
            cd MPlayer-${{env.version}}
            ./configure --disable-libmpeg2-internal \
                        --disable-ffmpeg_a \
                        --disable-gui \
                        --disable-mencoder \
                        --enable-runtime-cpudetection
            make -j4

      - name: Build package
        run: |
            cd MPlayer-${{env.version}}
            mkdir -p package/mplayer.app/Contents/MacOS/
            cp mplayer package/mplayer.app/Contents/MacOS/
            dylibbundler -od -b -x ./package/mplayer.app/Contents/MacOS/mplayer -d ./package/mplayer.app/Contents/MacOS/lib -p @executable_path/lib
            cd package
            tar -cvjf mplayer-macos.tar.bz2 mplayer.app/

      - name: Create artifact
        #if: ${{ false }}
        uses: actions/upload-artifact@v2
        with:
          name: mplayer-macos
          path: ./MPlayer-${{env.version}}/package/mplayer-macos.tar.bz2

      - name: Upload package to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./MPlayer-${{env.version}}/package/mplayer-macos.tar.bz2
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
